version: 2
updates:
  - package-ecosystem: npm
    directory: /typescript
    schedule:
      interval: weekly
    groups:
      playwright:
        patterns: ['@playwright/*', 'playwright']
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
